use sonic_bridge::pipeline::SonicPipeline;
use std::env;
use std::fs::File;
use std::io::Write;
use std::path::Path;

fn main() {
    let args: Vec<String> = env::args().collect();

    if args.len() < 2 {
        print_usage();
        return;
    }

    match args.len() {
        2 => {
            // 单音轨审美分析模式
            let audio_path = Path::new(&args[1]);
            println!("[*] Analyzing single track: {} ...", audio_path.display());

            match SonicPipeline::process_single(audio_path) {
                Ok((meta, segs)) => {
                    let mut report = Vec::new();
                    report
                        .push("# SonicBridge: LLM-Readable Music Descriptor (LRMD)\n".to_string());
                    report.push("> [!NOTE]".to_string());
                    report.push("> This is a physical-to-semantic acoustic report generated by SonicBridge. Pure-text LLMs can 'listen to' and 'appreciate' this track via this spatiotemporal matrix.\n".to_string());

                    report.push("## 1. Global Acoustic & Musicological Metadata".to_string());
                    report.push(format!("- **Filename**: `{}`", meta.filename));
                    report.push(format!(
                        "- **Duration**: `{:.2} seconds`",
                        meta.duration_seconds
                    ));
                    report.push(format!(
                        "- **Tempo (BPM)**: `{:.1} BPM` ({})",
                        meta.estimated_bpm, meta.tempo_feeling
                    ));
                    report.push(format!(
                        "- **Estimated Key**: `{}`\n",
                        meta.estimated_global_key
                    ));

                    report.push(
                        "## 2. Spatiotemporal Track Analysis (5-Second Intervals)".to_string(),
                    );
                    report.push("| Timeline | Chord | Dynamic Intensity | Timbral Brightness | Rhythmic & Transient Activity |".to_string());
                    report.push("| :--- | :--- | :--- | :--- | :--- |".to_string());

                    for seg in &segs {
                        report.push(format!(
                            "| **{}** | `{}` | {} | {} | {} |",
                            seg.time_range,
                            seg.chord,
                            seg.dynamic_level,
                            seg.timbre_brightness,
                            seg.rhythm_activity
                        ));
                    }

                    let report_text = report.join("\n");

                    // 保存到本地
                    let out_path = format!("{}.lrmd.md", args[1]);
                    if let Ok(mut file) = File::create(&out_path) {
                        let _ = file.write_all(report_text.as_bytes());
                        println!(
                            "[+] LRMD report successfully generated and saved to: {}",
                            out_path
                        );
                    }

                    println!("\n=== GENERATED LRMD REPORT PREVIEW ===");
                    println!("{}", report_text);
                }
                Err(e) => {
                    eprintln!("[-] Error processing audio track: {}", e);
                }
            }
        }
        3 => {
            // 双音轨比对模式
            let path_a = Path::new(&args[1]);
            let path_b = Path::new(&args[2]);
            println!(
                "[*] Running DTW Comparative Analysis:\n  - Track A: {}\n  - Track B: {}",
                path_a.display(),
                path_b.display()
            );

            match SonicPipeline::process_comparative(path_a, path_b) {
                Ok(report_text) => {
                    let out_path = format!(
                        "{}_vs_{}.lrmd.md",
                        path_a.file_stem().unwrap().to_str().unwrap(),
                        path_b.file_stem().unwrap().to_str().unwrap()
                    );
                    if let Ok(mut file) = File::create(&out_path) {
                        let _ = file.write_all(report_text.as_bytes());
                        println!(
                            "[+] Comparative LRMD report generated and saved to: {}",
                            out_path
                        );
                    }

                    println!("\n=== COMPARATIVE REPORT PREVIEW ===");
                    println!("{}", report_text);
                }
                Err(e) => {
                    eprintln!("[-] Error running comparative alignment: {}", e);
                }
            }
        }
        _ => {
            print_usage();
        }
    }
}

fn print_usage() {
    println!("SonicBridge CLI - LLM-Readable Acoustic Transformer");
    println!("Usage:");
    println!("  1. Single track analysis:      cargo run -- <path_to_audio>");
    println!("  2. Comparative version analysis: cargo run -- <path_to_track_A> <path_to_track_B>");
}
